# Generated by Django 4.1.4 on 2023-02-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=70, verbose_name='vin')),
                ('color', models.CharField(max_length=70, verbose_name='color')),
                ('brand', models.CharField(max_length=70, verbose_name='brand')),
                ('car_type', models.IntegerField()),
            ],
        ),
    ]
